{{- if gt (len .Values.disabledScrapers) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yet-another-aws-exporter.fullname" . }}-config
  labels:
    {{- include "yet-another-aws-exporter.labels" . | nindent 4 }}
data:
  yaae.yaml: |-
    disabledScrapers:
    {{- toYaml .Values.disabledScrapers | nindent 6 }}
{{- end }}
